### ISSUE TITLE
Update to last Jbrotli version

### ISSUE THREAD

**Issue by thelittlefireman** [MeteoGroup/jbrotli#20]
Hi, 
Do you plan to update to the latest Brotli version ? 

Thanks For All
Thomas

**Comment by nitram509** [comment]
Hi,

in principle yes :-)
But currently not enough time to focus on that project.

Regards
Martin

**Comment by thelittlefireman** [comment]
I could help you if you want. I started to watched thé build process but I don't understand all of the steps. Do you have à CI process ? Or somthing that i can Follow to start ?

I need to compile brotli, after that jbrotli and after jbrotli native that right ?

Thanks:)

**Comment by thelittlefireman** [comment]
I could help you if you want. I started to watched thé build process but I don't understand all of the steps. Do you have à CI process ? Or somthing that i can Follow to start ?

I need to compile brotli, after that jbrotli and after jbrotli native that right ?

Thanks:)
