### ISSUE TITLE
bintray repo delivering 302 -> 404

### ISSUE THREAD

**Issue by harryherbig** [MeteoGroup/jbrotli#21]
hey, we are trying to integrate your nice library into our play2 scala frontend for https://www.welt.de, but we can't resolve your dependency:

> [warn] ==== jcenter: tried
> [warn]   https://jcenter.bintray.com/org/meteogroup/jbrotli/jbrotli/0.5.0/jbrotli-0.5.0.pom

if i follow that link with curl it leads to a 404: 

```
curl -IL https://jcenter.bintray.com/org/meteogroup/jbrotli/jbrotli/0.5.0/jbrotli-0.5.0.pom                           
HTTP/1.1 302
Server: nginx
Date: Mon, 16 Apr 2018 20:31:27 GMT
Content-Length: 0
Connection: keep-alive
Location: https://repo.jfrog.org/artifactory/libs-release-bintray/org/meteogroup/jbrotli/jbrotli/0.5.0/jbrotli-0.5.0.pom?referrer

HTTP/1.1 404 Not Found
Content-Type: application/json;charset=ISO-8859-1
Date: Mon, 16 Apr 2018 20:31:28 GMT
Server: nginx
X-Artifactory-Id: repo.jfrog.org
X-Artifactory-Node-Id: artrjo-s1
X-Node: nginx-dedicated3c.prod-use1
Connection: keep-alive
```

this url works: 
`https://dl.bintray.com/nitram509/jbrotli/org/meteogroup/jbrotli/jbrotli-native-linux-x86-amd64/0.5.0/jbrotli-native-linux-x86-amd64-0.5.0.pom` but I dont know how to configure the resolver to reach that url

we followed the integration guide from https://github.com/guardian/play-brotli-filter

can you help us?

**Comment by harryherbig** [comment]
I am very sorry, we were too stupid to configure our Resolvers in our multi module Play2 Project.
Everything works fine!

**Comment by nitram509** [comment]
Harry, thank you for sharing your experience.
You're welcome.
