### ISSUE TITLE
Compile with GCC 4.8

### ISSUE THREAD

**Issue by rdblue** [MeteoGroup/jbrotli#4]
I've had to rebuild jbrotli for our environment using GCC 4.8. Everything works fine with 4.8, which is the default version that ships with Ubuntu 14.04 LTS. Compiling with 4.9 prevents jbrotli from working in several environments (including EMR), so I'd recommend building with 4.8. That would make the binary more portable and much easier to use in Hadoop. I also used CMake 2.8 instead of 3.0, without any problem.

**Comment by nitram509** [comment]
Thank you for this feedback.
Next release will be build, based on 4.8.

I plan to adopt the concourse-ci based build images, for easier maintenance.
I also plan to release within the next week.

**Comment by rdblue** [comment]
Wonderful! Thanks @nitram509!

**Comment by rdblue** [comment]
@nitram509, are you still planning a release soon?

I'd like to update HADOOP-13126, but it requires a release of jbrotli with #3 fixed. No rush since we're using a patched version, but I thought I'd check in to try getting this into Hadoop. Thanks!

**Comment by nitram509** [comment]
@rdblue

Ryan, thank you for this reminder.
I've released the [v0.5.0](https://github.com/MeteoGroup/jbrotli/releases/tag/v0.5.0)
which contains your your requested changes.

Thank you for you support
and I'm being happy and looking forward to see brotli support in Hadoop :-)

**Comment by rdblue** [comment]
Thanks @nitram509!
