### ISSUE TITLE
Not building with old GCC because of '-std=c++11' flag

### ISSUE THREAD

**Issue by kjatin** [MeteoGroup/jbrotli#8]
Is the flag "-std=c++11" really required in CMakeLists.txt? I removed this flag because my GCC was really old and still worked for me.
For some reasons, I don't have a control over the GCC of the machine where I build the code.

**Comment by nitram509** [comment]
Hi,

well spotted.
I copied it initially from brotli build files.
Meanwhile its no more present and I will remove it from jbrotli sources.

Thank you for reporting this.

Regards
Martin
